type User {
	joinTime: DateTime
	tweets(content: String): [Tweet]!
	userId: Int!
	username: String
}

type Tweet {
	content: String
	postTime: DateTime
	tweetId: Int!
	user: User!
	userId: Int
}

type DateTime {
	time: String
	unixTime: String
}

type Query {
	tweet(tweetId: Int): Tweet
	tweets(userId: Int, content: String): [Tweet]!
	user(userId: Int): User
	users(username: String): [User]!
}

schema {
	query: Query
	# mutation: Mutation
}
